export const GET_PAYMENT = "GET PAYMENT";
export const GET_PAYMENT_SUCCESS = "GET PAYMENT SUCCESS";
export const GET_ONE_PAYMENT = "GET ONE PAYMENT";
export const GET_ONE_PAYMENT_SUCCESS = "GET ONE PAYMENT SUCCESS";
export const GET_ONE_PAYMENT_START = "GET ONE PAYMENT START";
export const ADD_PAYMENT_INIT = "ADD PAYMENT INIT";
export const ADD_PAYMENT = "ADD PAYMENT";
export const ADD_PAYMENT_SUCCESS = "ADD PAYMENT SUCCESS";

export const EDIT_PAYMENT_DONE = "EDIT PAYMENT DONE";
export const EDIT_PAYMENT_INIT = "EDIT PAYMENT INIT";
export const EDIT_PAYMENT_SUCCESS = "EDIT PAYMENT SUCCESS";

export const LOADING = "LOADING";
export const ERROR_OCCURED = "ERROR_OCCURED";